default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', 'postgresql://postgres:postgres@localhost/lernedeutsch_development') %>

test:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', 'postgresql://postgres:postgres@localhost/lernedeutsch_test') %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
