service: lernedeutsch
image: ghcr.io/$KAMAL_REGISTRY_USERNAME/lernedeutsch

primary_role: bot

servers:
  bot:
    hosts:
      - $DEPLOY_HOST

healthcheck:
  disabled: true

builder:
  arch: amd64

ssh:
  user: deploy

registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - TELEGRAM_BOT_TOKEN
    - DATABASE_URL

